---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  pre_tasks:
    - name: Run Pre-tasks
      include_role:
        name: pre_tasks
      tags:
        - always
  tasks:
    - name: Install OpenSSL package
      package:
        name: openssl
        state: present

    - name: Install Terraform
      include_role:
        name: terraform
      tags:
        - terraform
    
    - name: Install Packer
      include_role:
        name: packer
      tags:
        - packer

    - name: Install Kubectl
      include_role:
        name: kubectl
      tags:
        - kubectl

    - name: Install Helm
      include_role:
        name: helm
      tags:
        - helm


