#############################################################
# Proxmox variables
#############################################################
variable "proxmox_hostname" {
  description = "Proxmox host address"
  type = string
  default = "https://192.168.1.1:8006"
}

variable "proxmox_username" {
  description = "Proxmox username (e.g. root@pam)"
  type = string
}

variable "proxmox_password" {
  description = "Proxmox password"
  type = string
}

variable "proxmox_node" {
  description = "Proxmox node"
  type = string
}

variable "proxmox_insecure_skip_tls_verify" {
  description = "Proxmox host address (e.g. https://192.168.1.1:8006)"
  type = bool
  default = true
}

#############################################################
# Template variables
#############################################################
variable "template_name" {
  description = "VM template name"
  type = string
  default = "centos-7-x86-64-minimal-1908-template"
}

variable "template_description" {
  description = "VM template description"
  type = string
  default = "Ubuntu 18-04-4 (generated by Packer)"
}


variable "vm_id" {
  description = "VM template ID"
  type = number
}

variable "vm_memory" {
  description = "VM amount of memory"
  type = number
  default = 2048
}

variable "vm_sockets" {
  description = "VM amount of CPU sockets"
  type = number
  default = 1
}

variable "vm_cores" {
  description = "VM amount of memory"
  type = number
  default = 2
}

variable "vm_storage_pool" {
  description = "Storage where template will be stored"
  type = string
  default = "local-lvm"
}

variable "vm_username" {
  description = "Default username"
  type = string
  default = "deploy"
}

variable "vm_user_password" {
  description = "Default user password"
  type = string
}

variable "vm_iso_file" {
  description = "ISO file location. (e.g: <proxmox_storage_name>:iso/ubuntu-18-04-4-server-amd64.iso)"
  type = string
}

variable "vm_time_zone" {
  description = "Time Zone"
  type = string
  default = "UTC"
}